name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive project
        run: |
          tar czf advensecret.tar.gz package.json next.config.js jsconfig.json src public

      - name: Decode SSH key
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        run: |
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > $HOME/VFix.pem
          chmod 600 ${HOME}/VFix.pem

      - name: Copy project to Vfix server
        env:
          IP: ${{secrets.IP}}
        run: |
          scp -i $HOME/VFix.pem -o StrictHostKeyChecking=no advensecret.tar.gz ubuntu@$IP:~
        
      - name: Deploy project to Vfix server
        env:
          IP: ${{secrets.IP}}
        run: |
          ssh -i $HOME/VFix.pem -o StrictHostKeyChecking=no ubuntu@$IP "
            rm -rf advensecret-temp
            mkdir -p advensecret-temp &&
            tar xf advensecret.tar.gz -C advensecret-temp 2> /dev/null &&
            rm advensecret.tar.gz &&
            cd advensecret-temp &&
            find . -name '._*' -exec rm {} \; &&
            npm i &&
            npm run build &&
            cd .. &&
            rm -rf advensecret &&
            mv advensecret-temp advensecret &&
            cd advensecret &&
            pm2 delete advensecret --silent &&
            pm2 start npm --name 'advensecret' -- start
          "
        